### ISSUE TITLE
Setup infrastructure to make an automated release

### ISSUE THREAD

**Issue by niclas86** [commonprofiles-care/fhir#68]
We have done a small change, the pull request #66 
We want to give Mangala and Vadim a try to release with the information provided by @peturv

**Comment by niclas86** [comment]
@peturv will make a release soon with 1.0.2

**Comment by niclas86** [comment]
The PR has been released, @claudiaehr will do the release

**Comment by niclas86** [comment]
We want to be able to do a deployment from an action when a valid tag has been created

**Comment by vadi2** [comment]
In addition to building when a tag has been created, we need to deploy the output to https://commonprofiles.care using SFTP.

Actions to do:
- [x] create a new job to build when a [semver tag](https://github.com/commonprofiles-care/fhir/issues/101) in `master` has been created that will both validate the tag format and create `output.zip` with the IG: https://github.com/commonprofiles-care/fhir/issues/103
- [x] create SFTP credentials for the upload job: https://github.com/commonprofiles-care/fhir/issues/104
- [x] create a separate job to deploy the IG output to https://commonprofiles.care using SFTP: https://github.com/commonprofiles-care/fhir/issues/105
- [ ] update build job to generate new [package-list.json](https://commonprofiles.care/fhir/package-list.json) and [history.html](https://commonprofiles.care/fhir/history.html): https://github.com/commonprofiles-care/fhir/issues/113
- [ ] test the upload solution with a sample release: https://github.com/commonprofiles-care/fhir/issues/106
- [ ] document release automation at a high level: https://github.com/commonprofiles-care/fhir/issues/107

https://commonprofiles.care is a wordpress website run by Niclas and Petur.

**Comment by vadi2** [comment]
We missed a step in planning, [package-list.json](https://commonprofiles.care/fhir/package-list.json) and [history.html](https://commonprofiles.care/fhir/history.html) need to be dynamically updated for the new release. Created a ticket for this.

**Comment by vadi2** [comment]
Mention: look at https://www.argentixinfo.com/ig/howtopub/index.html#using-ig-publishers--go-publish-function for the complete list instructions on how to publish a new release.
